"""add_val_hash_to_activity

Revision ID: 1eabbb5dfc53
Revises: dd8d9b581644
Create Date: 2025-12-08 20:49:21.098140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1eabbb5dfc53'
down_revision: Union[str, None] = 'dd8d9b581644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activitytable', sa.Column('val_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_activitytable_val_hash'), 'activitytable', ['val_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activitytable_val_hash'), table_name='activitytable')
    op.drop_column('activitytable', 'val_hash')
    # ### end Alembic commands ###
