"""add average_temperature to activitytable

Revision ID: 26fb1a703709
Revises: 7a8c53a1db55
Create Date: 2026-04-12 12:10:01.940028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26fb1a703709'
down_revision: Union[str, None] = '7a8c53a1db55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activitytable', sa.Column('average_temperature', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activitytable', 'average_temperature')
    # ### end Alembic commands ###
