"""Add ftp and power_zones to User

Revision ID: 498e1784fc38
Revises: bd76627883ed
Create Date: 2025-12-07 13:28:59.602495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '498e1784fc38'
down_revision: Union[str, None] = 'bd76627883ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ftp', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('power_zones', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'power_zones')
    op.drop_column('user', 'ftp')
    # ### end Alembic commands ###
