"""Add power curve to User

Revision ID: 7101bb794c7a
Revises: 498e1784fc38
Create Date: 2025-12-07 15:12:43.101531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7101bb794c7a'
down_revision: Union[str, None] = '498e1784fc38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('power_curve', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'power_curve')
    # ### end Alembic commands ###
