"""Cache static map

Revision ID: 71e958d38bed
Revises: 1e14421f75fb
Create Date: 2024-11-27 21:14:57.289684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e958d38bed'
down_revision: Union[str, None] = '1e14421f75fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activitytable', sa.Column('static_map', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activitytable', 'static_map')
    # ### end Alembic commands ###
