"""Add heart rate columns to ActivityBase

Revision ID: 7a8c53a1db55
Revises: 1eabbb5dfc53
Create Date: 2026-04-11 20:03:45.922394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a8c53a1db55'
down_revision: Union[str, None] = '1eabbb5dfc53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activitytable', sa.Column('average_heartrate', sa.Integer(), nullable=True))
    op.add_column('activitytable', sa.Column('max_heartrate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activitytable', 'max_heartrate')
    op.drop_column('activitytable', 'average_heartrate')
    # ### end Alembic commands ###
