"""add_activity_type_to_activitytable

Revision ID: 8b8ece57fd3c
Revises: 71e958d38bed
Create Date: 2025-05-21 20:28:34.816606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Added import for sqlmodel if needed, though sa is usually enough for ops


# revision identifiers, used by Alembic.
revision: str = '8b8ece57fd3c'
down_revision: Union[str, None] = '71e958d38bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activitytable', sa.Column('activity_type', sa.String(), nullable=False, server_default='recorded'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activitytable', 'activity_type')
    # ### end Alembic commands ###
