"""add_fit_file_and_parsed_at_to_activity

Revision ID: ac70e053a7a0
Revises: 13ea984b9f7d
Create Date: 2025-06-13 17:51:17.719542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac70e053a7a0'
down_revision: Union[str, None] = '13ea984b9f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activitytable', sa.Column('fit_file', sa.LargeBinary(), nullable=True))
    op.add_column('activitytable', sa.Column('fit_file_parsed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activitytable', 'fit_file_parsed_at')
    op.drop_column('activitytable', 'fit_file')
    # ### end Alembic commands ###
