"""Adding tags

Revision ID: bd76627883ed
Revises: ac70e053a7a0
Create Date: 2025-06-14 16:23:14.536592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd76627883ed'
down_revision: Union[str, None] = 'ac70e053a7a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activitytable', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activitytable', 'tags')
    # ### end Alembic commands ###
