"""rename calories to total_work

Revision ID: dd8d9b581644
Revises: e32010e555c3
Create Date: 2025-12-07 18:19:47.950968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd8d9b581644'
down_revision: Union[str, None] = 'e32010e555c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('activitytable', sa.Column('total_work', sa.Integer(), nullable=True, server_default=sa.text('0')))
    # op.drop_column('activitytable', 'calories')
    op.add_column('historicalstats', sa.Column('total_work', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.drop_column('historicalstats', 'calories')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historicalstats', sa.Column('calories', sa.INTEGER(), nullable=False))
    op.drop_column('historicalstats', 'total_work')
    op.add_column('activitytable', sa.Column('calories', sa.INTEGER(), nullable=True))
    op.drop_column('activitytable', 'total_work')
    # ### end Alembic commands ###
