"""Add HistoricalStats

Revision ID: e32010e555c3
Revises: 7101bb794c7a
Create Date: 2025-12-07 17:12:12.452569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e32010e555c3'
down_revision: Union[str, None] = '7101bb794c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historicalstats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('moving_time', sa.Float(), nullable=False),
    sa.Column('elapsed_time', sa.Float(), nullable=False),
    sa.Column('elevation_gain', sa.Float(), nullable=False),
    sa.Column('activity_count', sa.Integer(), nullable=False),
    sa.Column('max_power', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period_type', 'period_id', name='unique_user_period_stats')
    )
    op.create_index(op.f('ix_historicalstats_period_id'), 'historicalstats', ['period_id'], unique=False)
    op.create_index(op.f('ix_historicalstats_period_type'), 'historicalstats', ['period_type'], unique=False)
    op.add_column('activitytable', sa.Column('max_power', sa.Integer(), nullable=True))
    op.add_column('activitytable', sa.Column('average_power', sa.Integer(), nullable=True))
    op.add_column('activitytable', sa.Column('calories', sa.Integer(), nullable=True))
    # op.alter_column('activitytable', 'distance',
    #            existing_type=sa.FLOAT(),
    #            nullable=True)
    # op.alter_column('activitytable', 'active_time',
    #            existing_type=sa.FLOAT(),
    #            nullable=True)
    # op.alter_column('activitytable', 'elevation_gain',
    #            existing_type=sa.FLOAT(),
    #            nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('activitytable', 'distance',
    #            existing_type=sa.FLOAT(),
    #            nullable=False)
    # op.alter_column('activitytable', 'active_time',
    #            existing_type=sa.FLOAT(),
    #            nullable=False)
    # op.alter_column('activitytable', 'elevation_gain',
    #            existing_type=sa.FLOAT(),
    #            nullable=False)
    op.drop_column('activitytable', 'calories')
    op.drop_column('activitytable', 'average_power')
    op.drop_column('activitytable', 'max_power')
    op.drop_index(op.f('ix_historicalstats_period_type'), table_name='historicalstats')
    op.drop_index(op.f('ix_historicalstats_period_id'), table_name='historicalstats')
    op.drop_table('historicalstats')
    # ### end Alembic commands ###
